homeassistant:

  customize: !include customize.yaml
  packages: !include_dir_named packages/

frontend: !include frontend.yaml

lovelace:
  mode: yaml
  resources:
    - url: /local/custom-ui/alarm-keypad-card.js
      type: js
    - url: /local/custom-ui/alarm-group-state-card.js
      type: js
    - url: /local/community/lovelace-home-feed-card/lovelace-home-feed-card.js
      type: js

  dashboards:
    lovelace-default:
      mode: yaml
      filename: ui-keypad.yaml
      title: Keypad
      icon: mdi:security
      show_in_sidebar: true
      require_admin: false

mqtt:
  broker: 127.0.0.1
  username: USERNAME
  password: PASSWORD
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'
  discovery: true
  discovery_prefix: homeassistant

